-- Ensure lazy is first
require("configs._lazy-nvim")
--

-- -- Must be loaded immediately
-- require("configs.onedark-nvim")
-- require("configs.dashboard-nvim")
-- require("configs.nvim-web-dev-icons")
-- require("configs.nvim-highlight-colors")
-- require("configs.which-key-nvim")
-- -- Must be loaded before first input
-- require("configs.telescope-nvim")
-- require("configs.lualine-nvim")
-- require("configs.nvim-treesitter")
-- -- Must be loaded between Loading initials and Opening file
-- require("configs.oil-nvim")
-- require("configs.harpoon")
-- -- Must be loaded while Opening file
-- require("configs.gitsigns-nvim")
-- require("configs.nvim-cmp")
-- require("configs.conform-nvim")
-- require("configs.nvim-lspconfig")
-- require("configs.luasnip")
-- require("configs.undotree")
-- require("configs.nvim-dap")
-- require("configs.indent-blankline-nvim")
-- require("configs.rustaceanvim")
-- require("configs.virt-column-nvim")
-- require("configs.toggleterm-nvim")
-- require("configs.vim-illuminate")
-- require("configs.nvim-surround")
-- require("configs.crates-nvim")
